language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, 7.0, hhvm]

matrix:
  fast_finish: true
  include:
    # Test symfony versions
  - php: 5.3
    env: 'SYMFONY_VERSION=2.3.*'
  - php: 5.5
    env: 'SYMFONY_VERSION=2.7.*'
  - php: 5.6
    env: 'SYMFONY_VERSION=2.8.*'
  - php: 5.6
    env: 'SYMFONY_VERSION=3.0.*'
    # Test lowest 2.*
  - php: 5.3.3
    env: |
      COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
      PHPUNIT_COVERAGE='--coverage-text --coverage-clover=coverage.clover'
    # Test lowest 3.*
  - php: 5.6
    env: |
      SYMFONY_VERSION=3.0.*
      COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  allow_failures:
  - php: hhvm
  - php: 7.0

sudo: false

before_script:
  - mkdir -p build/logs
  # Ensure symfony & twig versions
  - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update symfony/framework-bundle=${SYMFONY_VERSION}; fi;
  # Remove fabpot/php-cs-fixer because it changes dependencies
  - composer remove --no-update --dev -n fabpot/php-cs-fixer;
  # Install packages
  - composer self-update;
  - composer update ${COMPOSER_FLAGS} --no-interaction;

script:
  - vendor/bin/phpunit ${PHPUNIT_COVERAGE};

after_script:
  - if [ "${PHPUNIT_COVERAGE}" != "" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "${PHPUNIT_COVERAGE}" != "" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

cache:
  directories:
  - $HOME/.composer/
